### ISSUE TITLE
Folder select option

### ISSUE THREAD

**Issue by nabeelbader** [arivera12/BlazorDownloadFile#10]
Just want to say, this library was really helpful to me today. Is there a possibility it would support a folder select option? Right now, it defaults to the downloads directory.

**Comment by arivera12** [comment]
As far as I know this is a browser specific setting. 

You would need to disable the browser default directory download behavior to prompt the folder dialog and choose where to save the file.

Take a look of this link and see if helps.

https://stackoverflow.com/questions/27525256/prompt-a-download-location-instead-of-downloading-directly

**Comment by nabeelbader** [comment]
Yes! Thats exactly what I needed to know. Thank you.
