### ISSUE TITLE
Enhancement: Can you show an example of how to get the "Filename" from a `<a>` element

### ISSUE THREAD

**Issue by Smurf-IV** [arivera12/BlazorDownloadFile#11]
Can you show an example of how to get the "Filename" from a `<a>` element so that it can be passed into you code for the FileSave ?

e.g. something like
- Create injected `<a>` element with a dummy `application/unknown` encoding that will _probably_ force the `SaveAs` to popup
- Get the href / filename / url / whatever from the link after the dummy file has been created.
- Pass that into you File Saving functionality to replace the file.

Maybe a useful link:
https://stackoverflow.com/questions/61802606/download-file-from-asp-net-core-api-from-blazor-client-application/61803104#61803104

**Comment by arivera12** [comment]
I don't understand what you want. Let's see if I understand, you have and `<a>` element holding the filename and you want to get the file name from that element from blazor context?

**Comment by arivera12** [comment]
I still read it again and I still don't understand what you want. This library already creates an `<a>` element hidden and gets clicked for you to trigger the file download.

**Comment by Smurf-IV** [comment]
I'll download the demo again, 
The reason I ask, is that I don't see the "Save As" dialog popup, only an image viewer. So if it's a hidden <a> then it is not doing the File "SaveAs" action.

**Comment by arivera12** [comment]
Someone asked me for that some days ago take a look of this https://github.com/arivera12/BlazorDownloadFile/issues/10#issuecomment-663337652

**Comment by Smurf-IV** [comment]
#10 is not what I am asking..
I'm asking for your demo app to show how to get the target filename that the user has selected, to use as the input to your functions.

**Comment by arivera12** [comment]
Take a look of this https://github.com/arivera12/BlazorDownloadFile/blob/master/BlazorDownloadFile.Demo/Pages/Index.razor

**Comment by arivera12** [comment]
In the demo you pass the filename into the DownloaFile as well the source of the data. 

If you want to get the filename from `<a>` lets say for example you have something like this:

`<a download="MyFile.pdf">Download</a>` 

To extract the filename from dowload attribute you will need to interop with JavaScript.

For this you need to Inject the JsRuntime:

`[Inject] IJSRuntime JSRuntime { get; set; }`

After that execute `document.querySelector` with the selector of the element you want to take.

I will update demo with a working example using `ElementReference` and native selector extracting the filename and dummy contenttype attribute.

It's this what you are asking?

**Comment by Smurf-IV** [comment]
> It's this what you are asking?

Yes please

**Comment by arivera12** [comment]
This is not related to this library but related to JavaScript and the JsRuntime, but I may add a sample somewhere attached here.

**Comment by arivera12** [comment]
```
<span @ref=MyElementReference download="myfile.txt" onclick=getFileName>Hello, world!</span>

@code {
  ElementReference MyElementReference;
  [Inject] public IJSRuntime JSRuntime { get; set; }
  async Task getFileName()
  {
    Console.WriteLine(await JSRuntime.InvokeAsync<string>("eval", $"document.querySelector('[_bl_{MyElementReference.Id}]').getAttribute('download')"));
  }
}
```

This is one dirty one liner approach but there are more ways of doing it based on the `querySelector` you may use.

You could or couldn't use `ElementReference` approach that is something you decide when to use it or not. 

`ElementReference` just adds the `id` attribute with a random generated value to the element, so this would be same as adding the `id` attribute with a value to the element manually.

If you know JavaScript and know how to do DOM manipulation this works the same with blazor using the `JsRuntime` class.

For extra reference please visit and read the info the links:

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1

https://blazor-university.com/javascript-interop/calling-javascript-from-dotnet/passing-html-element-references/
