### ISSUE TITLE
V 2.0.0 has "Confused" default overloads

### ISSUE THREAD

**Issue by Smurf-IV** [arivera12/BlazorDownloadFile#14]
When assuming one can use default values, the following is returned in the compiler
![image](https://user-images.githubusercontent.com/2418812/88784177-a2c79380-d187-11ea-86c7-8622fc6b59cf.png)

**Comment by arivera12** [comment]
One cancellation token is when reading the stream(the first one), the other cancellation token is when interop with JavaScript(the second one).

**Comment by arivera12** [comment]
You will still need to specify the contentType or the buffersize so the compiler doesn't get confused and know which method to use.

**Comment by arivera12** [comment]
There is not too much I could do here those overload are needed, if I remove default values developers would still need to specify them, one thing I could do it's remove the default values but I want to left them for reference for the developers to know which value should be safe or ok to use.
