### ISSUE TITLE
V 2.0 `DownloadFile` does not return an error state if the file is not downloaded

### ISSUE THREAD

**Issue by Smurf-IV** [arivera12/BlazorDownloadFile#15]
I'm passing a "Known" fully encoded URI filename into the `DownloadFile` API, and then testing for it's existence, but nothing is being returned to say that a fialure has occurred. (Exception etc.

Currently this should fail because it is being used in a Mocked JSInterop environment (BUnit) and therefore no js script function should succeed.

**Comment by arivera12** [comment]
There is not too much I can do here, wrap the entire function inside try and catch block and return what is thrown and null when everything is ok.

**Comment by arivera12** [comment]
For implementation reference:

https://www.w3schools.com/js/js_errors.asp

**Comment by arivera12** [comment]
## Brainstorming

As far as I know, on this operation of downloading a file, JavaScript won't return any succeeded state when running the download process but it could maybe raise an error somewhere. 

So as much I can do it's wrap the entire functions execution into `try` and `catch` block and if something it's raised save the error object and expose it to c#.

### ~~Models~~

~~`JavaScriptError`~~

~~This model should contain this properties:~~

- ~~Name~~
- ~~Message~~

### ~~Methods~~

~~`AnyJavaScriptError()`~~

~~This method should return a `bool` whether or not a JavaScript error occurred when downloading a file.~~

~~`ClearJavaScriptError()`~~

~~This method should clear the variable holding the JavaScript error object.~~

~~`GetJavaScriptError()`~~

~~This method should return an object of type of `JavaScriptError`.~~


### Models

`DowloadFileResult`

This model contains this properties:

- ErrorName
- ErrorMessage
- Succeeded

### All download file methods now returns an object of type `ValueTask<DowloadFileResult>`

**Comment by arivera12** [comment]
### New package available

`Install-Package BlazorDownloadFile -Version 2.1.0`

### Here are the release notes:

https://www.nuget.org/packages/BlazorDownloadFile/2.1.0
