### ISSUE TITLE
Before calling `_blazorDownloadFileBuffersPush` should the existing buffers be cleared first

### ISSUE THREAD

**Issue by Smurf-IV** [arivera12/BlazorDownloadFile#16]
If the previous download had been cancelled (e.g. Due to a user moving away from the page etc),
then the next call to 
`await DownloadFileService.DownloadFile(fileDetails.OriginalFileName, stream, cancellationToken, cancellationToken, bufferSize: 32*1024);`
Would also include the previous files buffers ?

**Comment by arivera12** [comment]
This is something is left open for the developers to manage when they are using the `AddBuffer` method. 

There is a `ClearBuffers` method which manage this. 

Every time you call `DownloadFile` and runs entirely, the buffers gets cleared automatically after execution is completed. 

If something is appended to the buffer it's not cleared by default, on navigating out side of the page I could catch that one, but if a task is cancelled by cancellation token does developer should get notified that the execution of the method have been canceled? 

I don't see any other way to handle this. 

The buffered method I think it could handle this by default, but the method that are not buffered could makes sense clear buffer before executing the JavaScript part. 

I will think and analyze it in the weekend to see where and where not should go.

**Comment by Smurf-IV** [comment]
The `_blazorDownloadFileBuffersPush` is used internally for when downloading the whole file.
Knowledge of the internals is not known.

> the buffers gets cleared automatically after execution is completed

The example of cancellation is not classed a completion.

Therefore the "whole file" method needs to call clearBuffers before starting any Add####.

**Comment by arivera12** [comment]
> The `_blazorDownloadFileBuffersPush` is used internally for when downloading the whole file.

Not in all cases

> Therefore the "whole file" method needs to call clearBuffers before starting any Add####.

I will analyze where and where not this make sense to be done.
