### ISSUE TITLE
Enhancement: DownloadBinaryBuffers Needs to have a CancellationToken versions

### ISSUE THREAD

**Issue by Smurf-IV** [arivera12/BlazorDownloadFile#18]
Currently only this exists
`public ValueTask<DowloadFileResult> DownloadBinaryBuffers(string fileName, string contentType = "application/octet-stream")`

The same will also need to be applied to the other direct `Download####` calls as well

**Comment by arivera12** [comment]
I miss that one. I apologize for this I will add it ASAP.

### TODO 

Add overloads  `CancellationToken` and `TimeSpan` to `DownloadBase64Buffers` and `DownloadBinaryBuffers`

**Comment by arivera12** [comment]
### Release

`Install-Package BlazorDownloadFile -Version 2.1.1`
