### ISSUE TITLE
Struggling with .xlsx file

### ISSUE THREAD

**Issue by proskilly** [arivera12/BlazorDownloadFile#2]
I'm not sure where the fault lies here is the server side code 
`                return File(fileContents: excelFile,
                    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");`
excelFile is a byte array produced using the EPPlus.

Then client side :
`                byte[] bytes = await httpResponseMessage.Content.ReadAsByteArrayAsync();
                await BlazorDownloadFileService.DownloadFile("test555.xlsx", bytes);`

The file that is "downloaded" in the browser is corrupt and won't open in Excel. The file that is downloaded is twice as big as the proper/working version of the file that I save server side using EPPlus.

**Comment by arivera12** [comment]
~~@proskilly can you test that this excel opens correctly without going into the download process?~~

My bad I misunderstand.  

Can you attach this excel here so I can test it on test enviroment?

**Comment by arivera12** [comment]
As far as I can see and understand I think you may have problems reading and sending the file to the client, you told me that the file that is downloaded is twice as big as the proper/working version of the file. 

Have you watched the file stream length when streaming into the http client how big is and if bytes length matches with the server side excel file?

**Comment by proskilly** [comment]
I can't send you the file because it has sensitive info in for my client, but i'll try a simple test xlsx file in a bit.
The file I have been having problems with is 25,570 bytes on the server and 51,140 bytes (twice as big) when downloaded and the response content length is 51,140 when i look at it in Chrome dev tools.

**Comment by arivera12** [comment]
> I can't send you the file because it has sensitive info in for my client, but i'll try a simple test xlsx file in a bit.

Don't worry I understand.

> The file I have been having problems with is 25,570 bytes on the server and 51,140 bytes (twice as big) when downloaded and the response content length is 51,140 when i look at it in Chrome dev tools.

Its seems like your problem may be on the server side.

**Comment by proskilly** [comment]
Yes the problem was on the server side, I have resolved it now.
In EPPlus I was saving the file on the server then getting the file as a byte array which doubled up the size of the byte array.
Thanks.

**Comment by arivera12** [comment]
@proskilly I am glad you found and resolved your problem. Don't forget to star the repository.
