### ISSUE TITLE
Extend the "DownloadFile(string fileName, ..." methods with IProgress

### ISSUE THREAD

**Issue by StefH** [arivera12/BlazorDownloadFile#21]
Is it possible that you extend the DownloadFile methods with `IProgress<double> progress? = null` which reports the % done on the download?

As example see:
https://github.com/Tyrrrz/YoutubeExplode/blob/e3e9b391941b3ab7fccacd665a361339a791849d/YoutubeExplode/Internal/Extensions/StreamExtensions.cs#L19

**Comment by arivera12** [comment]
Yeah, it's possible.

When using the methods that are chunked from c# to javascript on the do-while/for loop I just need to provide a callback with the download progress.

**Comment by arivera12** [comment]
New release
Install-Package BlazorDownloadFile -Version 2.1.6

**Comment by arivera12** [comment]
@StefH give me feedback when ever u can. It would be great to test this feature.

**Comment by StefH** [comment]
Hello @arivera12,

Sorry, but I actually moved away from your project and created another project https://github.com/StefH/Blazor.DownloadFileFast which has some extra download speed increase in .net 5.0

**Comment by arivera12** [comment]
@StefH I saw already some days ago and also someone posted the same article you use for that extra download speed. I will be using that approach soon. Thanks for the share.
