### ISSUE TITLE
Can we support DownloadFileFromText with charset parameter or by default supporting special characters

### ISSUE THREAD

**Issue by stevanuswijaya** [arivera12/BlazorDownloadFile#22]
Can we support DownloadFileFromText with **charset** parameter or by default supporting special characters? I'm currently trying to create a CSV file with Swedish characters in it (ÄÅÖäåö).

But the result is wrong:

![image](https://user-images.githubusercontent.com/18435961/104206473-d9405480-542f-11eb-80a4-93906a3d1929.png)

It's working if I added the code as in the image.

![image](https://user-images.githubusercontent.com/18435961/104205911-3be52080-542f-11eb-882d-1fc0f14f29f0.png)

Thanks

**Comment by arivera12** [comment]
Seems weird to me, the `DownloadFileFromText `should be able to support all characters since it's utf-8 but not every charset maybe in the same encoding format when reading from any source. 

As you can see this extension method https://github.com/arivera12/BlazorDownloadFile/blob/3f6383d3bd4435aabbf5f920316cad8088e48808/BlazorDownloadFile/Extensions/StringExtensions.cs#L13

Encodes all text to bytes using utf8, are you sure your problem exactly or may reside over there?

I don't think this should be a JavaScript issue at all but maybe from c# encoding since JavaScript downloads the file as-is without any encoding or conversions.

If you can send me a repro I may fix it.

Can you confirm that **before sending** the text to the `DownloadFileFromText` method the text is correctly encoded and they get interpreted incorrectly after downloading and opening the file?

**Comment by arivera12** [comment]
That error can also occur with the text editor and how does it's interprets the characters. 

What software you are using to open the csv file? MS Excel?

**Comment by stevanuswijaya** [comment]
As you can see here, when I call BlazorDownloadFile, the string was still okay.

![image](https://user-images.githubusercontent.com/18435961/104561243-5db8f000-5647-11eb-8617-2ed9e8e42ff6.png)

I'm using MS Excel to open the csv file.

**Comment by arivera12** [comment]
Ok, good can you check which charset enconding is your MS Excel opening the csv file?

**Comment by arivera12** [comment]
Can you check if the .csv file opened in notepad to see if it's encoded wrongly?

**Comment by arivera12** [comment]
> Can you check if the .csv file opened in notepad to see if it's encoded wrongly?

If opened in notepad is wrong then I will expose the charset encoding as an option with a default value to prevent breaking changes on the api.

Please let me know asap.

**Comment by arivera12** [comment]
I would like also to know if after using the extension to base64encode does your encoding gets broken.

**Comment by stevanuswijaya** [comment]
I opened the bad the file with notepad++.

![image](https://user-images.githubusercontent.com/18435961/104712238-9bd71200-5722-11eb-8d28-1818bf24e82f.png)

The encoding: UTF-8
![image](https://user-images.githubusercontent.com/18435961/104712368-be692b00-5722-11eb-9018-3ad0b1897bc2.png)

But in excel:

![image](https://user-images.githubusercontent.com/18435961/104712312-b27d6900-5722-11eb-8f07-9b5c4dfb7c33.png)


The good file after changing the BlazorDownloadFile script in notepad++:
![image](https://user-images.githubusercontent.com/18435961/104712899-73034c80-5723-11eb-8220-028d58127ba2.png)

Encoding: UTF8-BOM
![image](https://user-images.githubusercontent.com/18435961/104712920-7f87a500-5723-11eb-9b26-5859c7969719.png)


In excel:

![image](https://user-images.githubusercontent.com/18435961/104712837-5cf58c00-5723-11eb-9319-d68952ded062.png)

**Comment by stevanuswijaya** [comment]
I tried to change the base64encode this code instead as you instructed

![image](https://user-images.githubusercontent.com/18435961/104714811-f4f47500-5725-11eb-8a3a-46654d3cf031.png)

and we still get same bad result

![image](https://user-images.githubusercontent.com/18435961/104714891-0b9acc00-5726-11eb-8dc7-a72c92669175.png)

**Comment by arivera12** [comment]
Thanks for the investigation and the input I will take a deeper look on it. 

Can you share any sample data for me in json format? 

So I can use it has a test case?

**Comment by arivera12** [comment]
Wait a minute I read this in a hurry, in notepad++ the file opened ok. But in excel is wrong but after changing the encoding file format in notepad++ the excel read ok?

**Comment by arivera12** [comment]
This seems to be an issue with excel on how interprets csv filed but not rather with this library and the download process. 

Reference:
https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically

**Comment by arivera12** [comment]
Please upload for me a test json data so I can retest those special chars there seems to be a workaround this in the reference link.

**Comment by stevanuswijaya** [comment]
Here is the test json, I had same issue with it. Let me know if you need more information.
[test data.zip](https://github.com/arivera12/BlazorDownloadFile/files/5828863/test.data.zip)

Sorry for late reply, I think we have a huge time difference and I was really busy at work :)

**Comment by arivera12** [comment]
New release
Install-Package BlazorDownloadFile -Version 2.1.4

@stevanuswijaya I didn't had time to test  your attached file data but it should work for you out of the box. 

I am in a hurry. 

Please try out this new package version. 

Take a look of this [commit ](https://github.com/arivera12/BlazorDownloadFile/commit/c590d7fee1af8a2839a94aeab297fb49a9b59886) for more details. 

I turned on by default `encoderShouldEmitUTF8Identifier` so this should work for you out of the box. 

Please try it out and give me your feedback when ever it's possible.

**Comment by stevanuswijaya** [comment]
Hi

Unfortunately, I still got same problem.

![image](https://user-images.githubusercontent.com/18435961/105165801-133be580-5b17-11eb-9ce1-d6abf3429764.png)

**Comment by arivera12** [comment]
Ok, give me a time so I can retest this with more free time, reopening.

**Comment by arivera12** [comment]
It's seems I got it working now.
![image](https://user-images.githubusercontent.com/5600102/105191441-745ebb80-5b0d-11eb-8a89-f12ff58a80c5.png)

**Comment by arivera12** [comment]
Install-Package BlazorDownloadFile -Version 2.1.5

Please give me feedback if this does work for you properly now!

**Comment by arivera12** [comment]
Install-Package BlazorDownloadFile -Version 2.1.6

`encoderShouldEmitUTF8Identifier` is now false as default please remember turning this option true when downloading the csv file.

**Comment by stevanuswijaya** [comment]
It's working properly now! Thanks for the help!
