### ISSUE TITLE
Download Excel file

### ISSUE THREAD

**Issue by ErnanMaisels** [arivera12/BlazorDownloadFile#23]
Hi, can you please show me how to download excel or csv file from list of objects?
thanks a lot.

**Comment by arivera12** [comment]
Hi,

You can use this method `DownloadFileFromText` after you are able to transform your list of objects to a string csv format.

Excel compatible software should be able to read .csv file without any issues.

There are plenty of libraries that does this job for you like for example: csvhelper or servicestack.text.

**Comment by arivera12** [comment]
Take note that MS Excel have encoding issues when opening csv files and I am currently working on how to fix it. Take a look of this issue https://github.com/arivera12/BlazorDownloadFile/issues/22

**Comment by ErnanMaisels** [comment]
thanks a lot.

I used this (on the controller):

` var stream = new MemoryStream();
                await stream.WriteAsync(Encoding.UTF8.GetPreamble());
                await using (var writeFile = new StreamWriter(stream, leaveOpen: true))
                {
                    var csv = new CsvWriter(writeFile, CultureInfo.InvariantCulture, true);
                    await csv.WriteRecordsAsync(response);
                }
                stream.Position = 0; 
                return File(stream, "text/csv");`
and this (in client - WASM):

`        await BlazorDownloadFileService.DownloadFileAsync($"{siteName}_{DateTime.Now.Date}.csv", responsesToFile);
`

**Comment by arivera12** [comment]
Does Encoding.UTF8.GetPreamble() fixed the excel encoding issue for you?

**Comment by ErnanMaisels** [comment]
yes, it is (for Hebrew letters).

**Comment by arivera12** [comment]
So weird that this didn't worked for me on the mentioned issue 
`Convert.ToBase64String(new UTF8Encoding(encoderShouldEmitUTF8Identifier).GetBytes(plainText));`

I will give it a try to `Encoding.UTF8.GetPreamble()`

**Comment by ErnanMaisels** [comment]
Espero que esto ayude.
Contame.

**Comment by arivera12** [comment]
> Espero que esto ayude.
> Contame.

Hablas español? o usastes el traductor de google? jeje

**Comment by ErnanMaisels** [comment]
Nací en Argentina, pero desde los 6 años (1983) vivo en Israel

**Comment by arivera12** [comment]
Aqui un amigo desarrollador puertorriqueño jeje

**Comment by ErnanMaisels** [comment]
¡Un amigo que me ayudó mucho!

**Comment by arivera12** [comment]
Funciono gracias amigo!
![image](https://user-images.githubusercontent.com/5600102/105191441-745ebb80-5b0d-11eb-8a89-f12ff58a80c5.png)

**Comment by arivera12** [comment]
Install-Package BlazorDownloadFile -Version 2.1.5

**Comment by arivera12** [comment]
Install-Package BlazorDownloadFile -Version 2.1.6

`encoderShouldEmitUTF8Identifier` is now false as default please remember turning this option true when downloading the csv file if you don't set the `Encoding.UTF8.GetPreamble()` yourself.
