### ISSUE TITLE
Unable to download an exe file

### ISSUE THREAD

**Issue by ltemimi** [arivera12/BlazorDownloadFile#24]
Hi

I am unable to download an exe file I get "error reload the page" yet I am able to download exe files from websites so I do not think it is a system or browser settings issue.

I am able to download msi files .

Thanks

Laz

**Comment by arivera12** [comment]
How do you are downloading the file? As a stream or byte[]?

**Comment by ltemimi** [comment]
yes as a stream of bytes

`` var bytes = FileHelper.GetFileBytes(filePatch);
        var result = await BlazorDownloadFileService.DownloadFile(fileToDownload, bytes, "application/octet-stream");
``

**Comment by arivera12** [comment]
can you share any screenshot of the error? How big is the file?

**Comment by ltemimi** [comment]
<img width="1152" alt="EXEDownload" src="https://user-images.githubusercontent.com/5493492/105524681-df5bee00-5cd7-11eb-9fe9-7fa9ee1aa5f2.png">

all other files (bigger) download OK issue just with exe file

**Comment by arivera12** [comment]
This error seems or may be related to this one https://github.com/arivera12/BlazorDownloadFile/issues/25

**Comment by arivera12** [comment]
Pretty weird the other bigger files downloads ok but not the exe file...

**Comment by ltemimi** [comment]
Hi

I increased the buffer size and I am now able to download my 110MB exe file but it takes 2 minutes for the download dialog to appear. I am using Blazor server app.

Is there a way of speeding the download up?

Thanks

**Comment by arivera12** [comment]
Thats something I forgot to ask about... 

If it's blazor wasm or blazor server. 

Blazor server transmit data using signal r and there are limitations on this. 

I left those notations in the main readme.md of this repository

Take a look of this where I do left written some performance considerations and understandings.

https://github.com/arivera12/BlazorDownloadFile#performance-considerations-and-understandings

The next link is the signal r documentation and based on this you need to do buffer management based on your signal r `ApplicationMaxBufferSize` and `TransportMaxBufferSize`

`ApplicationMaxBufferSize` is the incoming connection buffer size

 `TransportMaxBufferSize` is the outgoing connection buffer size (This is the one you need to increase download speed)

https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-3.1#buffer-management

Based on this you need to download your file using the overload methods which manages the download buffer internally.

https://github.com/arivera12/BlazorDownloadFile/blob/10b471cec9ea1812bd0213df0968318348f0c08a/BlazorDownloadFile/Service/BlazorDownloadFileService.cs#L255

**Comment by arivera12** [comment]
> Hi
> 
> I increased the buffer size and I am now able to download my 110MB exe file but it takes 2 minutes for the download dialog to appear. I am using Blazor server app.
> 
> Is there a way of speeding the download up?
> 
> Thanks

Answering your question:

You can speed up download by increasing the buffer size.

**Comment by arivera12** [comment]
> I increased the buffer size and I am now able to download my 110MB exe file but it takes 2 minutes for the download dialog to appear. I am using Blazor server app.

How much did you increased the buffer size and where did you increase it?

Blazor server app?

Or on blazor download file method?

Both sides?

**Comment by ltemimi** [comment]
```
 endpoints.MapBlazorHub(o =>
                {
                    o.TransportMaxBufferSize = 1024*128;
                    o.ApplicationMaxBufferSize = 1024*128;
                });

 var result =  await BlazorDownloadFileService.DownloadFile(fileToDownload, bytes, 1024*64);
```
The signal R buffer increase do  not make any difference to the loading of the file from the server to be downloaded by the client

I am grateful for the help

**Comment by arivera12** [comment]
> ```
>  endpoints.MapBlazorHub(o =>
>                 {
>                     o.TransportMaxBufferSize = 1024*128;
>                     o.ApplicationMaxBufferSize = 1024*128;
>                 });
> 
>  var result =  await BlazorDownloadFileService.DownloadFile(fileToDownload, bytes, 1024*64);
> ```
> 
> The signal R buffer increase do not make any difference to the loading of the file from the server to be downloaded by the client
> 
> I am grateful for the help

The only way to speed up download speed is to increase the buffer size here

 `BlazorDownloadFileService.DownloadFile(fileToDownload, bytes, 1024*64);
`

Bigger the buffer size, bigger are the chunks that are send from the server to the client.

Take note that your internet service provider speed is also a variant on your download speed.

As far I know there is nothing else we can do to speed up download rather than just increasing the download buffer size.

**Comment by arivera12** [comment]
Since this question was asked only for downloading exe file and you asked me about download speed I created a new issue for that. Please refer to this issue since downloading the exe file was already resolved for you. https://github.com/arivera12/BlazorDownloadFile/issues/27
