### ISSUE TITLE
namespaces not fount 

### ISSUE THREAD

**Issue by franciscodeasis** [arivera12/BlazorDownloadFile#29]
hi i justinstall the package and  import in my program.cs the
 builder.Services.AddBlazorDownloadFile();
 and when i am trying to use this line in a blazor page  
 [Inject]
    public IBlazorDownloadFileService BlazorDownloadFileService { get; set; }

i got this error:

Error CS0246 Type or namespace name 'IBlazorDownloadFileService' not found (is a using directive or assembly reference missing?)

i try too using the @inject IBlazorDownloadFileService BlazorDownloadFileService but stilll got the same error.

i am using WPA with 5.NET

**Comment by arivera12** [comment]
I have not tried blazor download file with .net5 since I found lot of incompatibilities and broken api. Can you share a reproduction of this error so I can take a look?

**Comment by franciscodeasis** [comment]
ok thank you, don't worry i just solved it by changing this line in the inject:
  public Blazor.DownloadFile.Interfaces.IBlazorDownloadFileService BlazorDownloadFileService { get; set; }
