### ISSUE TITLE
Add support for file encoding

### ISSUE THREAD

**Issue by MarvinKlein1508** [arivera12/BlazorDownloadFile#30]
We are generating a CSV file with a `StringBuilder`.

Once the StringBuilder is build we want to download the generated content as file with `BlazorDownloadFile`.

`await downloadService.DownloadFileFromText("StarMoney_SepaImport.csv", sb.ToString(), "text/plain");`

The file will be downloaded with UTF-8 encoding but we need ISO-8859-1 in our case. So it would be nice if we can pass the encoding to the download methods.

**Comment by arivera12** [comment]
Do you have any encoding issues? The encoding default encoding utf8 should work all cases.

**Comment by MarvinKlein1508** [comment]
@arivera12 no I just want to change the default encoding. However, I got a workaround for this working. When I use the byte[] method instead of the string one, it uses the correct encoding.

So I converted my string to a byte[] and then then byte[] to an ISO-8859-1 byte[]

**Comment by arivera12** [comment]
The download method downloads the text file as-is no file enconding or conversion is done or used at all.

**Comment by arivera12** [comment]
I will think about it and consider adding support for this.

**Comment by arivera12** [comment]
This feature is now available on version 2.3.0
