### ISSUE TITLE
Naming Issue - DowloadFileResult

### ISSUE THREAD

**Issue by ryanbuening** [arivera12/BlazorDownloadFile#31]
It appears that DowloadFileResult is missing an "n" => DownloadFileResult

![image](https://user-images.githubusercontent.com/812974/137969865-c9982aa7-b3a4-4d1d-8f99-4254a4997094.png)

https://github.com/arivera12/BlazorDownloadFile/blob/master/BlazorDownloadFile/Models/DowloadFileResult.cs#L3

**Comment by arivera12** [comment]
ahh yes I will fix this typo soon once I upgrade to net 5

**Comment by arivera12** [comment]
Please download latest version 2.3.0.
