### ISSUE TITLE
Downloading PDF in Firefox redirects to blob://

### ISSUE THREAD

**Issue by MarvinKlein1508** [arivera12/BlazorDownloadFile#35]
Hi!

Since a week we are having issues with downloading files in Firefox.

I have this piece of code:
```
public async override Task DownloadAsync(bool confirmed = false)
{
    using FbController2 fbController = new FbController2();
    var angebot = await Angebot.GetAngebotAsync(Angebotsnummer, fbController);

    if (angebot is not null)
    {

        PrintAngebotRegelsatz printRegeln = new PrintAngebotRegelsatz
        {
            ShowFooter = true,
            ShowHeader = true
        };


        PrintAngebot angebotPrinter = await PrintAngebot.CreateAsync(angebot, printRegeln, fbController);
        // Generates th PDF file and returns the full file path
        string filenameAngebotPdf = angebotPrinter.Print(GlobalConfig.Configuration.OutputPfad);
    
    
        await downloadService.DownloadFile($"AN-{Angebotsnummer}.pdf", await File.ReadAllBytesAsync(filenameAngebotPdf), "application/pdf");
        await downloadService.ClearBuffers();
    }

    _isDownloading = false;
}
```

As you can see, I want to download AN-XXXXX.pdf which becomes generated one line before. Downloading the PDF will result in Firefox redircet to a blob:// url which displays the PDF.
`blob:https://localhost:5001/275606a8-d314-4674-9f2d-44fa282e4da9`

I'm running Windows 10 Professional 21H1 64 Bit with Firefox  98.0.2 with German locale. It works in Chrome and Edge.

**Comment by arivera12** [comment]
Hi @MarvinKlein1508:

`await downloadService.DownloadFile($"AN-{Angebotsnummer}.pdf", await File.ReadAllBytesAsync(filenameAngebotPdf), "application/pdf");`

The IBlazorDownloadFileService has nothing to do based on the browser download behavior.

As you said: _It works in Chrome and Edge_

What I can do/provide to see if its works for firefox browser regular dowload behavior is adding another parameter like: 

`bool openInAnotherWindow = false`

Then you could try opening in another window setting `bool openInAnotherWindow = true`

Then we can see how firefox behaves and if it behaves properly.

Does this makes sense to you? 

**But FIRST after doing the thing I mentioned above:** 

Can you take a look on how your firefox browser is behaving on your computer?

Here is a link for that setting:

[https://support.mozilla.org/en-US/kb/change-firefox-behavior-when-open-file](https://support.mozilla.org/en-US/kb/change-firefox-behavior-when-open-file)

`await downloadService.ClearBuffers();`

This line is not required for the method you are calling for downloading a file, **you can remove it**.

**Comment by MarvinKlein1508** [comment]
@arivera12 this seems to be an issue with the current version of Firefox. It worked in Firefox as well. When I use the Firefox Developer Edition (which is already using Firefox 100) it works again there.

So this seems to be a temporary issue.

**Comment by arivera12** [comment]
@MarvinKlein1508 closing this issue for now, hope your bug over firefox gets fixed ASAP.
