### ISSUE TITLE
Doesn't appear to work for text or json files

### ISSUE THREAD

**Issue by rebelweb** [arivera12/BlazorDownloadFile#4]
I am trying to send a JSON file to user, but looking at the code this is made for more binary type files and not text files.

**Comment by arivera12** [comment]
Yes, this library indeed is made for binary type files only. 

One quick dirty and fast alternative is convert the string to byte array then to base64.

Here is an extension method for string types that should work properly
```
public static string Base64Encode(this string plainText) {
  var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(plainText);
  return System.Convert.ToBase64String(plainTextBytes);
}
```

I may need to take some time to analyze what should be the proper way to download a file as text from any format.

**Comment by arivera12** [comment]
> I am trying to send a JSON file to user, but looking at the code this is made for more binary type files and not text files.

In which datatype is your json? string? stream? byte array? I am assuming you have your json data on string, am I correct?

**Comment by rebelweb** [comment]
I am using string. Thanks for the response, I went ahead and used IJSRuntime. I tried converting to one of the data types you support and couldn't get it to work. I was missing the convert to UTF-8. 🤦‍♂️

**Comment by arivera12** [comment]
Check out the extension method I wrote here. It should work and help you.

**Comment by arivera12** [comment]
@rebelweb I added a new and tested method that manage file downloads from plain text.

`BlazorDownloadFileService.DownloadFileFromText(string fileName, string plainText, string contentType = "text/plain")`

Please update `Install-Package BlazorDownloadFile -Version 1.0.10`
