### ISSUE TITLE
Can "the buffer management" solution, also have a way of

### ISSUE THREAD

**Issue by arivera12** [arivera12/BlazorDownloadFile#7]
Can "the buffer management" solution, also have a way of 
- Starting a save
- Adding many buffers (as they are downloaded to save having to create a single monster ManyGB memory stream and blowing the blazor VM)
- Committing the save (Or auto dispose if exception thrown etc.)

As per a rework of the gist above ?

_Originally posted by @Smurf-IV in https://github.com/arivera12/BlazorDownloadFile/issues/5#issuecomment-655400394_

**Comment by arivera12** [comment]
@Smurf-IV sounds good for me but I started reworking this based on the gist. I started implementing this since was reported on my local machine but haven't time to finish this re implementation. I am planning for this weekend or next week to start working on this again. 

@Smurf-IV can you explain a little bit more detailed the points:
- Starting a save
- Commiting the save

Did you got into a case where you blow blazor vm when downloading a file to a stream object?

If yes things gets hard here then.

As far I can see there seems limitation from blazor side see this

https://stackoverflow.com/questions/59343706/save-large-file-created-with-cs-in-blazor

Resource Stuff to take in consideration

[Array Max Length](https://stackoverflow.com/questions/6154989/maximum-size-of-an-array-in-javascript#:~:text=However%2C%20the%20maximum%20length%20of,%3D%204%2C294%2C967%2C295%20%3D%204.29%20billion%20elements.
)

JS Side

Longest possible array could have 4,294,967,295 = 4.29 billion elements

So we need to check that the buffer array doesn't exceed this and if needed create as many new buffer needed to hold the rest of data

Loop all the buffers and add them into a single JavaScript blob object and dispose every element as they start moving to the blob object to prevent doubling the memory usage

**Comment by Smurf-IV** [comment]
> @Smurf-IV sounds good for me but I started reworking this based on the gist. I started implementing this since was reported on my local machine but haven't time to finish this re implementation. I am planning for this weekend or next week to start working on this again.

Cool

> @Smurf-IV can you explain a little bit more detailed the points:
Via use of OnClick, a function is called
- Create async streaming call (i.e. gRPC)
- Make request to start download
- Need to either get the real fileName, or use GetTemp
- Create fileName ready for Appending contents
- ForEach over the streamed data paylods, and append
- Close file (Commit)


> Did you got into a case where you blow blazor vm when downloading a file to a stream object?
> If yes things gets hard here then.

Yes ! with a file only 500MB!

> 
> As far I can see there seems limitation from blazor side see this
> https://stackoverflow.com/questions/59343706/save-large-file-created-with-cs-in-blazor

Thanks for the link (this is why saving each payload as they come down and then performing `GC.Collect(0 or 1 )` would help, as it would only be (upto) 4 MB in each payload -> memory stream -> ConverttoBase64 -> blobAppend -> GC.Collect

**Comment by Smurf-IV** [comment]
Only 256MB !
![image](https://user-images.githubusercontent.com/2418812/87156584-ce580c00-c2b4-11ea-89a1-4908f868ea7d.png)

**Comment by Smurf-IV** [comment]
**Smurf-IV**: And it fell over on a 52MB file, How Am I supposed to support 1GB !

**arivera12** : So you had firstly a memory exception when you reached 256 MB and after another try another exception after reaching 52 MB? Did I understand correctly?

**Comment by arivera12** [comment]
Not sure why we can't download a simple stream of whatever size, this sounds like a downside of blazor and more like a hack to work around with it. So to start grouping all the pieces. 

Blazor only support a stream no more than 256 MB, we will need to split the stream read into multiple streams that doesn't exceeds 256 MB and then send to JS chunks by chunks as implemented using the gist, delete chunk by chunk as they go to JS and then call the GC right?

**Comment by Smurf-IV** [comment]
> So you had firstly a memory exception when you reached 256 MB and after another try another exception after reaching 52 MB? Did I understand correctly?

Correct.

> Blazor only support a stream no more than 256 MB, 

I did not know this, but gRPC `stream implementation` is recommended to be only in chunks of 1MB, But can default to 4MB, so this is well under that ;-)

> we will need to split the stream read into multiple streams that doesn't exceeds 256 MB 

52MB conversion process seems to blow the VM, so will need to be below that, I tried doing the conversion process "manually" from stream -> byte[] -> stream dispose -> GC -> Base64stream -> byte = null -> GC -> jsInterop ` still goes Boom`

> and then send to JS chunks by chunks as implemented using the gist, delete chunk by chunk as they go to JS and then call the GC right?

Try and call GC between conversion phase as well (Make it an option as to what type, i.e. 0 or 1 and Optimised / forced; so that if the Blazor VM is "stressed" then it developer has options to try and keep it happy

**Comment by Smurf-IV** [comment]
What about this:
https://github.com/jimmywarting/StreamSaver.js

**Comment by arivera12** [comment]
I still think I may let buffer size and management open for developers to use what ever buffer size they want and left a notation of which is the max size they should use as buffer to prevent blazor VM blow as this may change in the future by MS.

**Comment by arivera12** [comment]
Another thing that developers should consider for this to work. 

We need to read the stream as soon its arrive the first chunk.

I think this may bypass the problem from blazor side not sure what may happen with the js interop we may still need to do some rigorous tests for this.

Smurf can you test this approach before I start this rework just to see that Blazor VM doesn't blow with this approach?

I have the impression that most developers that may run into this error are downloading the entire stream into memory instead of reading it chunk by chunk from the HttpClient when headers arrive.

But for this to be tested with js interop I may still need the buffer implementation.

Take a look of this resources:

[HttpCompletionOption](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpcompletionoption?view=netcore-3.1)

[buffer the response as soon as it gets a initial response](https://stackoverflow.com/questions/12533533/async-reading-chunked-content-with-httpclient-from-asp-net-webapi)

**Comment by Smurf-IV** [comment]
>We need to read the stream as soon its arrive the first chunk.

That's what `gRPC` enables it to do. I'll get an psuedo example tomorrow showing what it looks like in the Blazor Client.

Also this is what I had to do to get the upload working, as the blob into buffer and then send Blew the VM, so I had to use the streaming via js upload method, to send small chunks via gRPC (And the GC.Collect after each chunk to release memory Blob -> base 64 -> MemoryStream -> ByteString conversions.)

**Comment by Smurf-IV** [comment]
The following also includes the attempt to try and reclaim as much of the VM as possible before converting into the blob - This still did not work.

Areas of interest highlighted:

![image](https://user-images.githubusercontent.com/2418812/87241490-a505c000-c41b-11ea-9202-3cbda242aeed.png)

**Comment by arivera12** [comment]
`DownloadFile` method needs the buffer management to work properly it won't work at all as it is implemented by now. Thanks for the source code and highlights I really appreciate it. I will let you know when this is ready for testing.

**Comment by arivera12** [comment]
@Smurf-IV can you update to version 2.0.0 and try again?

**Comment by arivera12** [comment]
> Can "the buffer management" solution, also have a way of
> 
> * Starting a save
> * Adding many buffers (as they are downloaded to save having to create a single monster ManyGB memory stream and blowing the blazor VM)
> * Committing the save (Or auto dispose if exception thrown etc.)
> 
> As per a rework of the gist above ?
> 
> _Originally posted by @Smurf-IV in [#5 (comment)](https://github.com/arivera12/BlazorDownloadFile/issues/5#issuecomment-655400394)_

Talking again about the initial title. What kind of methods do you need or want to be exposed to the blazor context?

Can you share an interface with the methods and what you are expecting to be implemented?

**Comment by arivera12** [comment]
Regarding on some performance test I have done in this library is that, base64 string and byte[] performs faster than stream. Since there is not direct conversion between from stream to a JavaScript object its a little more expensive this task. It was very tricky understand how c# transform some data types when interop with JavaScript. When its base64 this is the most simple data type to work with but byte[] gets transformed into base64 string when transfered to JavaScript and for some reason it wont work properly when encoding cause its base64 representation turns to be something else. A list of bytes gets passed down as an array of byte with bytes numeric representation to JavaScript, this is the reason why I send a `IList<byte>` rather than `byte[]` to JavaScript. So if we get binary representation we just needed to call Uint8Array and push the binary representation entirely (better performance for JavaScript because less operations) into the array to then pass it down to the JavaScript native Blob object. It took me some days to understand this and how it works.

**Comment by arivera12** [comment]
Ok I have read the code a little more deeply.

You want to manage the buffers on your own instead of the library for you?

So, its seems you want some methods like this ones for example:

`AddBuffer(string base64)`
`AddBuffer(byte[] bytes)`
`AddBuffer(Stream stream)`
`ClearBuffers()`
`DownloadBuffers(string fileName, string contentType)`

**Comment by Smurf-IV** [comment]
Plus a way of getting the users choice of the initial file location to `Start` the process.

**Comment by arivera12** [comment]
> Plus a way of getting the users choice of the initial file location to `Start` the process.

What you mean by this? Like a From-To of the base64, bytes or stream?

If yes, why does this would make sense? I don't understand the point.

I think the way this should work is that you just push into the buffers

Then once you call `DownloadBuffers` method, the buffers gets downloaded into a single file 

And buffers gets cleared automatically.

Take note that letting the buffers management open for developers it could hit the browser performance 

And also turn into memory leaks also if the developer only calls `AddBuffer` and never call the `DownloadBuffers`.

**Comment by arivera12** [comment]
I haven't tested yet the methods but they should work properly as they are being used internally and mixed in the current tested methods. A new package will be release in few days after I update and test demo site.
