### ISSUE TITLE
Downloaded file - when saved - has an Extra null appended to the file

### ISSUE THREAD

**Issue by Smurf-IV** [arivera12/BlazorDownloadFile#9]
e.g download csv file and save,
Open in winmerge (Or some other tool that supports byte only alignment)
observe a null character at the end of the file.
This fails a "Signature check" because csv have to be ASCII chars only, i.e Alphanumerics with few extras (".,-) etc.
non-printables, back moves, and "Graphics" should fail.

![image](https://user-images.githubusercontent.com/2418812/88142868-27496d80-cbee-11ea-847a-78385f9650dc.png)

**Comment by arivera12** [comment]
Hmm, So  the original file doesn't have the trailing null character but when processed by the download file method its gets append?

**Comment by Smurf-IV** [comment]
> Original file doesn't have the trailing null character but when processed by the download file method its gets append?

Correct.
Notes:
- UnitTest have shown that the stored file on the server is correct
- streamed download of file is also correct
- Extra Null appears on Browser stored file

I think it is this line: https://github.com/arivera12/BlazorDownloadFile/blob/985f13f5ac846f5a935a7c92a48d58ae0c0ced21/BlazorDownloadFile/Extensions/StreamExtensions.cs#L15

**Comment by arivera12** [comment]
I will take a deep look on it. I think this weekend I will have some free time to invest on blazordownloadfile.

**Comment by arivera12** [comment]
Seems related https://github.com/arivera12/BlazorDownloadFile/issues/6

**Comment by arivera12** [comment]
Install-Package BlazorDownloadFile -Version 1.0.11

**Comment by Smurf-IV** [comment]
I have left comments on 
36bb3a2

**Comment by arivera12** [comment]
I reopen this one to keep track after we test this with the pure stream implementation without the memorystream casting

**Comment by arivera12** [comment]
@Smurf-IV take note that the buffered/partitioned implementation doesn't use the .ToByteArray() extension method.

**Comment by Smurf-IV** [comment]
comments left on de484d2
